# Site settings
title: Damon Chen
email: "damon@zhenchen.me"
description: "Damon Chen 的博客"
baseurl: ""
url: "http://www.zhenchen.me"
permalink: /:year/:title


# Social account
# twitter:  PeiwenLu
weibo:    2509911980
github:   zhenchentl
# codepen:  P233
# dribbble: username


# Comment
disqus_shortname: MarkChenTL


# Google Analytics
# google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap

# filter: category
